### PR TITLE
Add mean-flux suppression in learning scripts and processing script

### PR DESCRIPTION
**Pull request by jibanCat**
I add mean-flux suppression in both mean model and noise variance.

- The part of inserting indicator functions is slightly different from the scripts I had in multi-dla.
This is due to, when I was writing multi-dla scripts, I assumed Lyman alpha forest did not require an indicator (indicators before were only applied on Lyman beta, gamma, ... ); however, it is not true for the redshift code.

- A side-note: I was able to run processing script but I couldn't run the learning script. I keep getting minFunc error-

```
 Iteration   FunEvals     Step Length    Function Val        Opt Cond
Step direction is illegal!
Output argument "exitflag" (and maybe others) not assigned during call to
"minFunc".

Error in learn_qso_model (line 219)
    minFunc(objective_function, initial_x, minFunc_options);

Error in learn_sbatch_qsos (line 24)
learn_qso_model;
```

I spent lots of time try to debug; however, I found I also couldn't run the original learning script in sbird's zqsos2. So the error might be due to preloaded_qsos.mat or other issues not related to mean-flux modifications (hopefully!). If you have another preloaded_qsos.mat, I can try more tests.

- A minor question is: I see an indicator applied in the original processing script on omega (`this_omega2(ind_w) = .001;`), but I did not see any indicator applied in the previous learning script.

I guess that would not cause problem for pixel-wise omega since values larger than Lya were masked out during processing; but maybe that would cause the learning of effective optical depth in the noise variance slightly off(?)

- Note: my branch already merged my multi-dla codes. Those multi-dla codes are in different folders so easy to clean up. If you need me to delete them, I can add a commit to delete them in this pull request before you merge.

### CODE REVIEW

**Comment by sbird** [comment]
Thank you Ming-Feng! Merging!

**Review by sbird — APPROVED** [review]
Looks good!

**Comment by jibanCat** [comment]
Cool! Let me know if you have another preloaded_qsos.mat so that I can test the learning script again

**Comment by sbird** [comment]
Thanks - there are a couple of other changes I am making on top, will let you know...

**Comment by sbird** [comment]
In fact, I will make a branch and ask you to review the PR

**Comment by jibanCat** [comment]
> In fact, I will make a branch and ask you to review the PR

Sure! let me know!

I was testing `parfor`. It seems to work if `num_quasars` is small and the number of workers is not too large.

I had `num_quasars = 7` and `parpool(12)` run successfully on UCR cluster. Roughly 180-220secs per QSO (not sure if it is faster or not though).

I couldn't get to use `num_quasars = 15`. Keep getting Bus errors. I used 32 cores and 128 GB mem, which is already a large memory usage.

**Comment by sbird** [comment]
This is for processing? Interesting. 180-220 sec per QSO is not much faster than without the parfor.

**Comment by sbird** [comment]
There is a new preloaded_qsos.mat in the same place as the last one. Make sure you use the zqsos2 branch as I changed the normalisation.

**Comment by jibanCat** [comment]
> This is for processing? Interesting. 180-220 sec per QSO is not much faster than without the parfor.

Hmm ... then maybe parpool is not necessary. Not sure the reason. I remember in the multi-dla code using parpool is much faster than not using it. For multi-dla, I remember it was ~10 secs with 4 workers on my laptop, and ~2.5 secs with 32 workers on UCR cluster.



> There is a new preloaded_qsos.mat in the same place as the last one. Make sure you use the zqsos2 branch as I changed the normalisation.

Ok thanks!

**Comment by sbird** [comment]
hmm, odd. Maybe the extra memory usage with the 3D integration means the code is bottlenecked with memory accesses and doesn't get a boost from multi-core.

**Comment by jibanCat** [comment]
Yes I think the memory usage is the issue. While I was running parfor, I kept getting this warning: 

```
Warning: A worker aborted during execution of the parfor loop. The parfor loop
will now run again on the remaining workers
```

Though I have no proof, I guess they aborted because couldn't handle the memory usage

I am thinking if we break the large 100000 loop into a 10 outer loop and 10000 inner loop, maybe the parfor would work:

```matlab
% arrange zQSO samples into a (10, 10000) matrix 
for i in num_z_bins
    this_z_bin = all_z_bins(i, :);
    % num_dla_samples = 10000
    parfor j in num_dla_samples
        z_qso   = this_z_bin(1, j);
        z_dla    = sample_z_dla(j);
        log_nhi = log_nhi_samples(j);
end
```

I am just thinking but haven't tried. If the current code is working fine within a reasonable runtime, then probably it is unnecessary to make changes.

**Pull request merged**
